

SELECT * FROM CLIENTE

-- ALTERA A ORDEM DO RETORNO DOS DADOS
SELECT * FROM CLIENTE ORDER BY NOMECLIENTE

-- ALTERA A ORDER DO RETORNO USANDO O NÚMERO DA COLUNA
SELECT * FROM CLIENTE ORDER BY 3

-- ALTERA A ORDER DO RETORNO USANDO O NÚMERO DA COLUNA DECRESCENTE
SELECT * FROM CLIENTE ORDER BY 3 DESC

-- REMOVE OS RESULTADOS REPETIDOS
SELECT DISTINCT CIDADE FROM CLIENTE

-- FAZ JUNÇÃO DE DADOS
SELECT NOMECLIENTE + ' - ' + CPFCNPJ FROM CLIENTE

-- FAZ JUNÇÃO DE DADOS E RENOMEIA A COLUNA
SELECT NOMECLIENTE + ' - ' + CPFCNPJ AS NOME FROM CLIENTE

-- SELECIONA POR PARTE DO NOME
-- TODOS QUE COMEÇAM COM LETRA M
SELECT NOMECLIENTE FROM CLIENTE
 WHERE NOMECLIENTE LIKE 'C%O'

SELECT NOMECLIENTE FROM CLIENTE
 WHERE NOMECLIENTE LIKE '%C%'

-- O % SUBSSTITUI UMA CADEIA DE CARACTERES
-- O _ SUBISTUI SOMENTE UM CARACTER E NA POSIÇÃO ESPECÍFICA

-- TODOS QUE TEM 'A' NA SEGUNDA LETRA DO NOME
SELECT * FROM CLIENTE WHERE NOMECLIENTE LIKE '_A%'

-- PARA FAZER ESCAPE DO CARACTER % DEVE-SE COLOCÁ-LO ENTRE []
-- SELECIONAR QUEM TEM O CARACTER % NO NOME
SELECT * FROM CLIENTE WHERE NOMECLIENTE LIKE '%[%]%'

-- TOP ESPECIFICA A QUANTIDADE DE REGISTROS A SEREM RETORNADOS
-- SELECIONA OS 2 PRIMEIROS REGISTROS
SELECT TOP 2 * FROM CLIENTE

-- MOSTRA SOMENTE O 3 E O 4 REGISTRO
SELECT TOP 2 * FROM CLIENTE
 WHERE IDCLIENTE NOT IN (SELECT TOP 2 IDCLIENTE FROM CLIENTE)

-- PAGINAÇÃO DE DADOS -- ORDER BY É OBRIGATÓRIO
SELECT *
  FROM CLIENTE
 ORDER BY IDCLIENTE
 OFFSET 2 ROWS FETCH NEXT 2 ROWS ONLY

--------------------------------------------------------------
-- FUNÇÕES CALCULADAS DO BANCO DE DADOS
-- HÁ 5 FUNÇÕES - ESTAS SEMPRE RETORNAM UMA LINHA
--------------------------------------------------------------
-- MAX() - RETORNA O MAIOR VALOR DE UMA COLUNA
-- MIN() - RETORNA O MENOR VALOR DE UMA COLUNA
-- AVG() - AVERAGE - RETORNA A MÉDIA DOS VALORES DE UMA COLUNA
-- SUM() - RETORNA A SOMA DOS VALORES DE UMA COLUNA
-- COUNT() - RETORNA A CONTAGEM DAS LINHAS SELECIONADAS

SELECT MAX(IDCLIENTE) AS MAIOR FROM CLIENTE
SELECT MIN(IDCLIENTE) AS MENOR FROM CLIENTE
SELECT AVG(IDCLIENTE) AS MEDIA FROM CLIENTE
SELECT SUM(IDCLIENTE) AS SOMA  FROM CLIENTE
SELECT COUNT(*)		  AS NRLINHAS FROM CLIENTE

-- SELECIONAR QUANTAS PESSOAS MORAM EM CADA CIDADE
-- MOSTRAR O NOME DA CIDADE E A QTDE DE PESSOAS
SELECT ESTADO, CIDADE, COUNT(*) TOTAL
  FROM CLIENTE
 GROUP BY ESTADO, CIDADE
 ORDER BY TOTAL DESC

-- FAZENDO FILTRO DENTRO DESTA COLUNA CALCULADA
-- MOSTRANDO SOMENTE AS CIDADES QUE TEM MAIS DE 2 PESSOAS RESIDENTES
SELECT CIDADE, COUNT(*) AS TOTAL
  FROM CLIENTE
 GROUP BY CIDADE
HAVING COUNT(*) > 2
 ORDER BY 2

--==========================================================
-- FUNÇÕES DE DATA
--==========================================================
SELECT GETDATE()
SELECT @@LANGUAGE

SELECT * FROM SYSOBJECTS
SELECT * FROM sys.syslanguages

SELECT DATANASC, YEAR(DATANASC) AS ANO, MONTH(DATANASC) MES
  FROM CLIENTE

SELECT DATANASC, DATEDIFF(YEAR, DATANASC, GETDATE()) AS IDADE
  FROM CLIENTE

