
--======================================================
-- TIPO DE DADO DEFINIDO PELO USUÁRIO
--======================================================
-- PRIMEIRO CRIA O TIPO QUE SERÁ O PADRÃO PARA AS TABELAS
CREATE TYPE USR_NOME_COMPLETO
  FROM VARCHAR(40) NOT NULL

-- QUANDO FOR CRIAR UMA TABELA, AO INVÉS DE USAR O TIPO
-- PADRÃO DO BANCO DE DADOS, VOCÊ USA O SEU TIPO CRIADO
CREATE TABLE T01(
	ID		INT,
	NOME	USR_NOME_COMPLETO
)


DROP TABLE T01
DROP TYPE USR_NOME_COMPLETO






