--=====================================================================================
-- EXCLUSÃO DE DADOS DE TABELAS E VOLTA DO CONTADOR DE AUTOINCREMENTO (IDENTITY)
--=====================================================================================


DELETE FROM ITENSVENDA

DELETE FROM VENDA
DBCC CHECKIDENT('VENDA', RESEED, 0)

DELETE FROM PRODUTO
DBCC CHECKIDENT('PRODUTO', RESEED, 0)

DELETE FROM CLIENTE
DBCC CHECKIDENT('CLIENTE', RESEED, 0)

DELETE FROM CATEGORIA
DBCC CHECKIDENT('CATEGORIA', RESEED, 0)


--=====================================================================================
-- TABELA CATEGORIA
--=====================================================================================
INSERT INTO CATEGORIA VALUES ('MAT. INFORMÁTICA')
INSERT INTO CATEGORIA VALUES ('MAT. ESCRITÓRIO')
INSERT INTO CATEGORIA VALUES ('MAT. HIG. E LIMPEZA')
INSERT INTO CATEGORIA VALUES ('TINTAS E VERNIZES')
SELECT * FROM CATEGORIA

--=====================================================================================
-- TABELA PRODUTO
--=====================================================================================
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('TECLADO 105 TECLAS S/ FIO', 1, 'UND', 10, 3, 45.00);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('MONITOR 17" LCD AOC', 1, 'UND', 5, 2, 700.00);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('GABIENTE 4 BAIAS SATELLITE', 1, 'UND', 20, 5, 60.00);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('CANETA ESFEROGRÁFICA VERMELHA', 2, 'UND', 21, 10, 1.50);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('MONITOR 17" LG LCD', 1, 'UND', 7, 3, 750.00);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('TECLADO 105 TECLAS USB', 1, 'UND', 10, 4, 45.00);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('PEN DRIVE 1 GB KINGSTON', 1, 'UND', 15, 8, 50.00);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('PEN DRIVE 2 GB LG', 1, 'UND', 5, 8, 80.00);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('PAPEL A4', 2, 'RESMA', 15, 25, 10.90);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('PAPEL OFICIO', 2, 'RESMA', 15, 15, 11.90);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('PASTA A-Z ESTREITA', 2, 'UND', 18, 10, 2.50);
INSERT INTO PRODUTO (NOMEPRODUTO, IDCATEGORIA, UNIDADE, QTDEESTOQUE, QTDEESTOQUEMIN, VALORUNITARIO) VALUES ('PASTA CATÁLOGO', 2, 'UND', 5, 4, 8.30);

SELECT * FROM PRODUTO

--=====================================================================================
-- TABELA CLIENTE
--=====================================================================================

SELECT * FROM CLIENTE
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('CHICO BENTO', '98065354677', '20080203', NULL, 'ROÇA', 'NULL', 'SANTA ISABEL', 'SP')
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('CASCÃO', '68943176843', '20051015', 'RUA MAURÍCIO DE SOUSA, 999', 'LIMOEIRO', '87506080', 'SANTA ISABEL', 'SP')
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('ZÉ LELÉ', '48254309931', '2009-12-31', NULL, 'ROÇA', '87544220', 'SANTA ISABEL', 'SP')
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('CEBOLINHA', '78621539461', '20030525', 'RUA MAURÍCIO DE SOUSA, 950', 'LIMOEIRO', '87506080', 'SANTA ISABEL', 'SP')
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('JUCA CHAVES', '12345678901', '19500212', 'Rua Monteiro Lobato, 340', 'Centro', '81150000', 'Curitiba', 'PR');
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('CAROLINA CIBELE ANDRADE', '09786374635', '19800701', 'JOÃO MATOS DE ALUCIDAS, 740', 'VILA ZUMBI', '83405098', 'COLOMBO', 'PR');
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('MILENA CHINAYA DE FREITAS', '74837412894', '19701113', 'DALILA LOPES COSTA, 44', 'NOVO MUNDO', '81550897', 'CURITIBA', 'PR');
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('CRISTIANE DE FÁTIMA MENDES', '64737568637', '19820607', 'R. JOAO STENZOWSKI, 230', 'CIDADE INDUSTRIAL', '88020342', 'LAGUNA', 'SC');
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('KARINA MARQUES DE AZEVEDO', '35261098453', '19800101', 'JACOB GERMAN, 88', 'TATUQUARA', '83507548', 'ALMIRANTE TAMANDARÉ', 'PR');
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('SCHEILA HELENA MACEDO DO REIS', '35243874657', '19810127', 'RUA PONTA GROSSA, 90', 'CAPÃO DA IMBUIA', '80610160', 'CURITIBA', 'PR');
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('ROSA MARIA BERNARDINO', '63527348572', '19750110', 'RUA VICENTE NOGUEIRA, 900', 'ESPERANÇA', '83820055', 'FAZENDA RIO GRANDE', 'PR');
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('VIVIANE HELOISA DE MORAES', '84657307761', '19790208', 'TRAVESSA ELIZETI CARDOSO, 889', 'JARDIM IPANEMA', '89242432', 'FLORIANÓPOLIS', 'SC');
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('ELIANE PAULA DE ALENCAR', '31426485723', '19770101', 'VER. MIGUEL COSTA CURTA, 654', 'JARDIM GABINETO', '83408455', 'COLOMBO', 'PR');
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('ANA PAULA DE CARVALHO', '35471094154', '19750101', 'RUA GUGLIELMO MARCONI, 98', 'EUCALIPTOS', '80050299', 'ALMIRANTE TAMANDARE', 'PR');
INSERT INTO CLIENTE (NOMECLIENTE, CPFCNPJ, DATANASC, ENDERECO, BAIRRO, CEP, CIDADE, ESTADO) VALUES ('LUIZA CATARINA DE ALBUQUERQUE', '34576584938', '19811209', 'RUA ENG. ALBERTO MONTEIRO, 977', 'PORTÃO', '82810277', 'CURITIBA', 'PR');



--=====================================================================================
-- TABELA VENDA
--=====================================================================================

INSERT INTO VENDA (IDCLIENTE, DATAHORA, VALORTOTAL) VALUES (8, '20140827 10:44:29', 0.00);
INSERT INTO VENDA (IDCLIENTE, DATAHORA, VALORTOTAL) VALUES (8, '20140830 11:00:07', 0.00);
INSERT INTO VENDA (IDCLIENTE, DATAHORA, VALORTOTAL) VALUES (10, '20140903 09:03:03', 0.00);
INSERT INTO VENDA (IDCLIENTE, DATAHORA, VALORTOTAL) VALUES (4, '20140905 17:32:15', 0.00);


SELECT * FROM VENDA



--=====================================================================================
-- TABELA ITENSVENDA
--=====================================================================================
INSERT INTO ITENSVENDA (IDVENDA, IDPRODUTO, QTDE, VALORVENDA) VALUES (1, 1, 3, 45.00);
INSERT INTO ITENSVENDA (IDVENDA, IDPRODUTO, QTDE, VALORVENDA) VALUES (1, 5, 4, 750.00);
INSERT INTO ITENSVENDA (IDVENDA, IDPRODUTO, QTDE, VALORVENDA) VALUES (1, 6, 9, 45.00);
INSERT INTO ITENSVENDA (IDVENDA, IDPRODUTO, QTDE, VALORVENDA) VALUES (2, 6, 3, 45.00);
INSERT INTO ITENSVENDA (IDVENDA, IDPRODUTO, QTDE, VALORVENDA) VALUES (2, 10, 4, 11.90);
INSERT INTO ITENSVENDA (IDVENDA, IDPRODUTO, QTDE, VALORVENDA) VALUES (3, 10, 4, 11.90);
INSERT INTO ITENSVENDA (IDVENDA, IDPRODUTO, QTDE, VALORVENDA) VALUES (3, 1, 5, 45.00);
INSERT INTO ITENSVENDA (IDVENDA, IDPRODUTO, QTDE, VALORVENDA) VALUES (4, 3, 2, 60.00);


select * from ITENSVENDA


