
--================================
-- SELECT COM SUBSELECT
--================================

-- MOSTRAR TODAS AS CATEGORIAS QUE POSSUEM PRODUTOS CADASTRADOS

SELECT * FROM CATEGORIA
 WHERE IDCATEGORIA = 1
    OR IDCATEGORIA = 2
	
SELECT * FROM CATEGORIA
 WHERE IDCATEGORIA IN (1,2)

SELECT IDCATEGORIA FROM PRODUTO

SELECT * FROM CATEGORIA
 WHERE IDCATEGORIA IN (SELECT IDCATEGORIA FROM PRODUTO)

-- USANDO JOIN
SELECT *
  FROM CATEGORIA
 INNER JOIN PRODUTO
  ON CATEGORIA.IDCATEGORIA = PRODUTO.IDCATEGORIA


SELECT DISTINCT CATEGORIA.IDCATEGORIA, CATEGORIA.NOMECATEGORIA
  FROM CATEGORIA
 INNER JOIN PRODUTO
  ON CATEGORIA.IDCATEGORIA = PRODUTO.IDCATEGORIA

SELECT DISTINCT C.*
  FROM CATEGORIA AS C
 INNER JOIN PRODUTO AS P
  ON C.IDCATEGORIA = P.IDCATEGORIA

-- MOSTRAR OS NOMES DOS CLIENTES QUE TEM VENDAS CADASTRADAS
SELECT DISTINCT NOMECLIENTE
  FROM CLIENTE C
 INNER JOIN VENDA V ON C.IDCLIENTE = V.IDCLIENTE

-- MOSTRAR OS NOMES DOS CLIENTES QUE TEM VENDAS CADASTRADAS
-- E QUE ESTAS VENDAS FORAM FEITAS NO MÊS DE SETEMBRO/2014
SELECT DISTINCT NOMECLIENTE
  FROM CLIENTE C
 INNER JOIN VENDA V ON C.IDCLIENTE = V.IDCLIENTE
 WHERE V.DATAHORA >= '2014-09-01'
   AND V.DATAHORA <= '2014-09-30 23:59:59.999'

-- USANDO BETWEEN (ENTRE)
SELECT DISTINCT NOMECLIENTE
  FROM CLIENTE C
 INNER JOIN VENDA V ON C.IDCLIENTE = V.IDCLIENTE
 WHERE V.DATAHORA BETWEEN '2014-09-01' AND '2014-09-30 23:59:59.999'

SELECT DISTINCT NOMECLIENTE
  FROM CLIENTE C
 INNER JOIN VENDA V ON C.IDCLIENTE = V.IDCLIENTE
 WHERE MONTH(V.DATAHORA) = 9
   AND YEAR(V.DATAHORA) = 2014

-- USANDO PARTE DA SELEÇÃO ACIMA, MOSTRAR TAMBÉM O NOME DO MÊS
-- REMOVER O FILTRO DE MÊS DE SETEMBRO
SELECT C.NOMECLIENTE, MONTH(V.DATAHORA) AS MES,
		CASE MONTH(V.DATAHORA)
			WHEN 1  THEN 'JANEIRO'
			WHEN 2  THEN 'FEVEREIRO'
			WHEN 3  THEN 'MARÇO'
			WHEN 4  THEN 'ABRIL'
			WHEN 5  THEN 'MAIO'
			WHEN 6  THEN 'JUNHO'
			WHEN 7  THEN 'JULHO'
			WHEN 8  THEN 'AGOSTO'
			WHEN 9  THEN 'SETEMBRO'
			WHEN 10 THEN 'OUTUBRO'
			WHEN 11 THEN 'NOVEMBRO'
			WHEN 12 THEN 'DEZEMBRO'
		END AS NOMEMES		
  FROM CLIENTE C
 INNER JOIN VENDA V ON C.IDCLIENTE = V.IDCLIENTE
 WHERE YEAR(V.DATAHORA) = 2014

-- MOSTRAR O NOME DA CATEGORIA E A QUANTIDADE DE PRODUTOS
-- QUE TEM CADASTRADO PARA CADA UMA
SELECT IDCATEGORIA, NOMECATEGORIA,
	(SELECT COUNT(*) FROM PRODUTO WHERE 
		PRODUTO.IDCATEGORIA = CATEGORIA.IDCATEGORIA) AS QTDE
  FROM CATEGORIA

-- OUTRA FORMA DE FAZER, USANDO JOIN E GROUP BY
SELECT C.IDCATEGORIA, C.NOMECATEGORIA, COUNT(P.IDPRODUTO)
  FROM CATEGORIA C
  LEFT JOIN PRODUTO P ON C.IDCATEGORIA = P.IDCATEGORIA
 GROUP BY C.IDCATEGORIA, C.NOMECATEGORIA

-- MOSTRAR OS NOMES DAS CATEGORIAS QUE NÃO TEM
-- NENHUM PRODUTO CADASTRADO
SELECT C.*
  FROM CATEGORIA C
  LEFT JOIN PRODUTO P ON C.IDCATEGORIA = P.IDCATEGORIA
 WHERE P.IDPRODUTO IS NULL

/*	MOSTRAR A QUANTIDADE DE VEZES QUE FORAM FEITAS
	VENDAS A CADA CLIENTE.
	MOSTRAR O NOME DO CLIENTE E A QUANTIDADE */

/*	MOSTRAR O NOME DE TODOS OS CLIENTES QUE COMPRARAM
	O PRODUTO 'PAPEL OFICIO' */

/*	MOSTRAR O NOME DE TODOS OS PRODUTOS VENDIDOS
	NO MÊS DE SETEMBRO	*/

/*	MOSTRAR O NOME DO PRODUTO E A QUANTIDADE VENDIDA
	DE CADA UM	*/

