
--============================================
--	RESTRI플O POR CHECK
--============================================
CREATE TABLE T01(
	ID		INT NOT NULL,
	NOME	VARCHAR(40) NOT NULL
)

-- ADICIONA A COLUNA VALOR
ALTER TABLE T01 ADD VALOR MONEY
-- ALTER TABLE T01 DROP COLUMN VALOR}


SELECT * FROM T01

-- ADICIONA A RESTRI플O POR CHECK
ALTER TABLE T01 ADD CONSTRAINT CHK_T01
 CHECK (VALOR >= 0 AND VALOR <= 1000)

-- ALTER TABLE T01 DROP CONSTRAINT CHK_T01


-- TENTA INSERIR VALOR NEGATIVO
INSERT INTO T01 VALUES (1, 'ABC', -90)

-- RESTRI플O POR UNIQUE
ALTER TABLE T01 ADD CONSTRAINT UNK_T01
 UNIQUE (NOME)

-- INSERE PRIMEIRO NOME
INSERT INTO T01 VALUES (1, 'A', 10)

-- TENTA INSERIR O MESMO NOME
INSERT INTO T01 VALUES (2, 'A', 10)

-- APAGA A RESTRI플O DE UNIQUE
ALTER TABLE T01 DROP CONSTRAINT UNK_T01

-- APAGA A RESTRI플O DE CHECK
ALTER TABLE T01 DROP CONSTRAINT CHK_T01

-- APAGA A TABELA
DROP TABLE T01






SELECT *
  FROM SYSOBJECTS
 ORDER BY XTYPE

SELECT
	 (SELECT NAME FROM SYSOBJECTS S2
	   WHERE S2.id = S1.parent_obj) OBJPAI,
	S1.*
  FROM SYSOBJECTS S1
 ORDER BY XTYPE


SELECT S2.NAME AS OBJPAI, S1.*
  FROM SYSOBJECTS S1, SYSOBJECTS S2
 WHERE S2.id = S1.parent_obj
 ORDER BY S1.xtype







