--================================================
-- TRIGGER - GATILHO
--================================================
	É UM EVENTO QUE É EXECUTADO DIRETAMENTE SOBRE
UMA TABELA. OCORRE SEMPRE QUANDO HÁ ALGUMA OPERAÇÃO
DE DML QUE ALTERA DADOS (INSERT, DELETE e/ou UPDATE)
	UMA TRIGGER É DISPARADA ANTES e/ou DEPOIS DE
CADA EVENTO:
	- BEFORE INSERT (ANTES  DE INSERIR)
	- AFTER  INSERT (DEPOIS DE INSERIR)
	- BEFORE DELETE (ANTES  DE EXCLUIR)
	- AFTER  DELETE (DEPOIS DE EXCLUIR)
	- BEFORE UPDATE (ANTES  DE ATUALIZAR)
	- AFTER  UPDATE (DEPOIS DE ATUALIZAR)

	O SQL SERVER SEMPRE GERA TABELAS TEMPORÁRIAS
COM OS DADOS QUE FORAM INSERIDOS, EXCLUÍDOS OU
ATUALIZADOS
	- PARA UMA INSERÇÃO	   É CRIADA A TABELA INSERTED
	- PARA UMA EXCLUSÃO	   É CRIADA A TABELA DELETED
	- PARA UMA ATUALIZAÇÃO SÃO CRIADAS AS TABELAS
		INSERTED E DELETED
OBS: NO SQL SERVER NÃO EXISTE TRIGGERS BEFORE

-- TABELA PARA TRABALHAR COM TRIGGER
CREATE TABLE TABTRIGGER(
	ID		INT IDENTITY,
	NOME	VARCHAR(40)
)

-- TRIGGER SOBRE A TABELA
CREATE TRIGGER TRG_TABTRIGGER_INCLUI
	ON TABTRIGGER AFTER INSERT
AS
	SELECT 'DADOS INSERIDOS', * FROM INSERTED
GO

INSERT INTO TABTRIGGER VALUES ('MARCIA')
INSERT INTO TABTRIGGER VALUES ('LUIZA')
INSERT INTO TABTRIGGER VALUES ('MARCELA')


INSERT INTO TABTRIGGER VALUES ('JOANA'), ('CARLA')

-- TRIGGER DELETE
CREATE TRIGGER TRG_TABTRIGGER_EXCLUI
	ON TABTRIGGER AFTER DELETE
AS
	SELECT 'DADOS EXCLUÍDOS', * FROM DELETED
GO

DELETE FROM TABTRIGGER WHERE ID = 5

-- TRIGGER UPDATE
CREATE TRIGGER TRG_TABTRIGGER_ATUALIZA
	ON TABTRIGGER AFTER UPDATE
AS
	SELECT 'DADOS ANTIGOS', * FROM DELETED
	SELECT 'DADOS NOVOS'  , * FROM INSERTED
GO

SELECT * FROM TABTRIGGER
UPDATE TABTRIGGER SET NOME = 'ANA' WHERE ID = 2


--=================================================
-- TRIGGER SOBRE OS EVENTOS INSERT, DELETE E UPDATE
--=================================================
CREATE TRIGGER TRG_TABTRIGGER_I_D_U
	ON TABTRIGGER AFTER INSERT, DELETE, UPDATE
AS
	IF EXISTS(SELECT * FROM INSERTED) AND
	   EXISTS(SELECT * FROM DELETED)
	BEGIN
		PRINT 'INSTRUÇÃO DE UPDATE'
	END
	ELSE IF EXISTS(SELECT * FROM INSERTED)
	BEGIN
		PRINT 'INSTRUÇÃO DE INSERT'
	END
	ELSE IF EXISTS(SELECT * FROM DELETED)
	BEGIN
		PRINT 'INSTRUÇÃO DE DELETE'
	END
GO



INSERT INTO TABTRIGGER VALUES ('LUANA')

UPDATE TABTRIGGER SET NOME = 'LUANA PATRÍCIA'
	WHERE NOME = 'LUANA'


