INSERT INTO EMPRESTIMO_OBRA (ID_EMPRESTIMO, ID_EXEMPLAR, DATA_PREV_DEVOLUCAO, DATA_DEVOLUCAO)
	VALUES (2,5, '2015-05-25','2015-06-23')
	
	
	SELECT * FROM EMPRESTIMO_OBRA
	
	SELECT COUNT(*) FROM EXEMPLAR AS EX
					INNER JOIN EMPRESTIMO_OBRA AS EO
						ON EX.ID_EXEMPLAR = EO.ID_EXEMPLAR
					INNER JOIN EMPRESTIMO AS EM
						ON EO.ID_EMPRESTIMO = EM.DH_EMPRESTIMO
	
	SELECT COUNT(*)
						FROM EXEMPLAR AS EX
						INNER JOIN EMPRESTIMO_OBRA AS EO
							ON EX.ID_EXEMPLAR = EO.ID_EXEMPLAR
						INNER JOIN EMPRESTIMO AS EM
							ON EO.ID_EMPRESTIMO = EM.ID_EMPRESTIMO
						WHERE EM.ID_ALUNO = 5