--==========================================================
--LOGINS USUÁRIOS E GRUPOS
--==========================================================

-PAR O SQL SERVER UM LOGIN É APENAS UMA AUTORIZAÇÃO PARA CONEXÃO
COM O SGBD, JÁ UM USUARIO É UMA AUTORIZAÇÃO PARA CONEXÃO COM UM BANCO DE DADOS ESPECIFICO.
PARA CRIAR UM USUARIO PRIMEIRO É PRECISO CRIÁ-LO COM LOGIN.
HA DOIS TIPO DE AUTENTICAÇÃO
WINDOWS AUTHENTICATION MODE
SQL SERVER AND WINDOWS AUTHENTICATION MODE


--CRIAÇÃO DO LOGIN
CREATE LOGIN TESTE WITH PASSWORD = '123456'

--CRIAÇÃO DO USUARIO NO BANCO DE DADOS
USE TRABAV2
CREATE USER TESTE

--PERMISSÃO DE SELECT SOBRE A TABELA ALUNO
GRANT SELECT ON ALUNO TO TESTE

--PERMISSÃO POR CAMPO DE TABELA
GRANT SELECT ON AUTOR (ID_AUTOR, NOME_AUTOR) TO TESTE

--REMOVER A PERMISSÃO
REVOKE SELECT ON ALUNO TO TESTE 

--=====================================================
--ROLE - (PAPEIS) GRUPOS 
--=====================================================
--PAPEIS SÃO FUNÇOES ADMINISTRATIVAS, DADO QUE É MAIS FACIL
--GERENCIAR GRUPOS DO QUE CADA USUARIO
--INDIVIDUALMENTE QUANDO HA UM GRANDE NUMEROS DE USUARIOS

--CRAS-SE UM GRUPO(PAPEL), CONCEDE OU NEGA AS PERMISSÕES AO GRUPO.
--DESTA FORMA O USUARIO HERDA TODAS AS PERMISSÕE DO GRUPO.

--CRIAÇÃO DO GRUPO
CREATE ROLE TELEATENDENTE

--ADICIONA O USUARIO NO GRUPO
SP_ADDROLEMEMBER TELEATENDENTE, TESTE

--RETIRA USUARIO DO GRUPO
SP_DROPROLERMEMBER TELEANTENDENTE, TESTE

--PERMISSÃO AO GRUPO
GRANT SELECT ON ALUNO TO TELEATENDENTE

--=================================================================
--UMA PERMISSÃO NEGADA TEM PRIORIDADE SOBRE UMA PERMISSÃO CONCEDIDA
--=================================================================

--=========================================
--PARA REVOGAR UMA CONCESSÃO OU UMA NEGAÇÃO
REVOKE SELECT ON VENDA TO TELEATENDENTE