
-- COMENTÁRIO DE UMA LINHA
/*
	COMENTÁRIO DE MAIS DE UMA LINHA
*/

USE SISTEMACOMERCIAL

--===========================================================
-- TABELA CATEGORIA
--===========================================================
CREATE TABLE CATEGORIA(
	IDCATEGORIA		INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMECATEGORIA	VARCHAR(40) NOT NULL
)

--===========================================================
-- TABELA PRODUTO
--===========================================================
CREATE TABLE PRODUTO(
	IDPRODUTO		INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMEPRODUTO		VARCHAR(50)	NOT NULL,
	IDCATEGORIA		INT NOT NULL,
	UNIDADE			VARCHAR(20),
	QTDEESTOQUE		INT DEFAULT 0,
	QTDEESTOQUEMIN	INT,
	VALORUNITARIO	MONEY,
	ATIVO			CHAR(1) DEFAULT 'S',
	-- CHAVE ESTRANGEIRA
	FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA
		ON UPDATE CASCADE
)

--===========================================================
-- TABELA CLIENTE
--===========================================================
CREATE TABLE CLIENTE(
	IDCLIENTE		INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMECLIENTE		VARCHAR(50) NOT NULL,
	CPFCNPJ			VARCHAR(14) NOT NULL,
	DATANASC		DATE,
	RGIE			VARCHAR(20),
	ENDERECO		VARCHAR(50),
	BAIRRO			VARCHAR(40),
	CEP				VARCHAR(8),
	CIDADE			VARCHAR(40),
	ESTADO			CHAR(2)
)
--===========================================================
-- TABELA CLIENTETELEFONE
--===========================================================
CREATE TABLE CLIENTETELEFONE(
	IDCLIENTETELEFONE	INT NOT NULL PRIMARY KEY IDENTITY,
	IDCLIENTE			INT NOT NULL,
	TELEFONE			VARCHAR(11) NOT NULL,
	TIPO				CHAR(1)	-- F - FIXO / C - CELULAR
	-- CHAVE ESTRANGEIRA
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE
		ON UPDATE CASCADE
)
--===========================================================
-- TABELA CLIENTEEMAIL
--===========================================================
CREATE TABLE CLIENTEEMAIL(
	IDCLIENTEEMAIL		INT NOT NULL PRIMARY KEY IDENTITY,
	IDCLIENTE			INT NOT NULL,
	EMAIL				VARCHAR(100),
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE
		ON UPDATE CASCADE
)

--===========================================================
-- TABELA VENDA
--===========================================================
CREATE TABLE VENDA(
	IDVENDA		INT NOT NULL PRIMARY KEY IDENTITY,
	IDCLIENTE	INT NOT NULL,
	DATAHORA	DATETIME DEFAULT GETDATE(),
	VALORTOTAL	MONEY,
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE
		ON UPDATE CASCADE
)
--===========================================================
-- TABELA ITENSVENDA
--===========================================================
CREATE TABLE ITENSVENDA(
	IDVENDA			INT NOT NULL,
	IDPRODUTO		INT NOT NULL,
	QTDE			INT NOT NULL,
	VALORVENDA		MONEY NOT NULL,
	-- CHAVE PRIMARIA
	PRIMARY KEY(IDVENDA, IDPRODUTO),
	-- CHAVES ESNTRANGEIRAS
	FOREIGN KEY (IDVENDA) REFERENCES VENDA
		ON UPDATE CASCADE,
	FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO
		ON UPDATE CASCADE
)

--===========================================================
-- TABELA FORNECEDOR
--===========================================================
CREATE TABLE FORNECEDOR(
	IDFORNECEDOR	INT NOT NULL PRIMARY KEY IDENTITY,
	RAZAOSOCIAL		VARCHAR(100) NOT NULL,
	NOMEFANTASIA	VARCHAR(100) NOT NULL,
	CNPJ			VARCHAR(14) NOT NULL,
	IE				VARCHAR(20),
	ENDERECO		VARCHAR(50),
	BAIRRO			VARCHAR(40),
	CEP				VARCHAR(8),
	CIDADE			VARCHAR(40),
	ESTADO			CHAR(2)
)

--===========================================================
-- TABELA FORNECEDORTELEFONE
--===========================================================
CREATE TABLE FORNECEDORTELEFONE(
	IDFORNECEDORTELEFONE	INT NOT NULL PRIMARY KEY IDENTITY,
	IDFORNECEDOR			INT NOT NULL,
	TELEFONE				VARCHAR(11) NOT NULL,
	TIPO					CHAR(1)	-- F - FIXO / C - CELULAR
	-- CHAVE ESTRANGEIRA
	FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR
		ON UPDATE CASCADE
)

--===========================================================
-- TABELA FORNECEDOREMAIL
--===========================================================
CREATE TABLE FORNECEDOREMAIL(
	IDFORNECEDOREMAIL		INT NOT NULL PRIMARY KEY IDENTITY,
	IDFORNECEDOR			INT NOT NULL,
	EMAIL					VARCHAR(100),
	FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR
		ON UPDATE CASCADE
)

--===========================================================
-- TABELA COMPRA
--===========================================================
CREATE TABLE COMPRA(
	IDCOMPRA		INT NOT NULL PRIMARY KEY IDENTITY,
	IDFORNECEDOR	INT NOT NULL,
	DATAHORA		DATETIME DEFAULT GETDATE(),
	VALORTOTAL		MONEY,
	FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR
		ON UPDATE CASCADE
)

--===========================================================
-- TABELA ITENSCOMPRA
--===========================================================
CREATE TABLE ITENSCOMPRA(
	IDCOMPRA		INT NOT NULL,
	IDPRODUTO		INT NOT NULL,
	QTDE			INT NOT NULL,
	VALORCOMPRA		MONEY NOT NULL,
	-- CHAVE PRIMARIA
	PRIMARY KEY(IDCOMPRA, IDPRODUTO),
	-- CHAVES ESNTRANGEIRAS
	FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA
		ON UPDATE CASCADE,
	FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO
		ON UPDATE CASCADE
)











