-- UPDATE DE UM REGISTRO
UPDATE CLIENTE
   SET CEP = '81150000'
 WHERE IDCLIENTE = 1

-- UPDATE DE MAIS DE UM REGISTRO
UPDATE CLIENTE
   SET CEP = '81150000', 
       BAIRRO = 'LIMOEIRO'
 WHERE IDCLIENTE = 1



