
use SISTEMACOMERCIAL
--====================================================
-- VIEW - VISÃO
--====================================================
-- É UMA FORMA DE SELECIONAR DADOS DE UMA TABELA
-- OU MAIS, CRIANDO UMA PSEUDOTABELA

-- PRODUTOS QUE ESTÃO ABAIXO DO MÍNIMO
SELECT * FROM PRODUTO
 WHERE QTDEESTOQUE < QTDEESTOQUEMIN

-- TRANSFORMAR ESTA CONSULTA EM UMA VIEW
CREATE VIEW VW_PRODUTOS_ABAIXO_MINIMO
AS
SELECT * FROM PRODUTO
 WHERE QTDEESTOQUE < QTDEESTOQUEMIN

--SELEÇÃO NESTA VIEW
SELECT * FROM VW_PRODUTOS_ABAIXO_MINIMO

-- FILTRO NA VIEW
SELECT * FROM VW_PRODUTOS_ABAIXO_MINIMO
 WHERE UNIDADE = 'UND'


SELECT IDPRODUTO, NOMEPRODUTO
  FROM VW_PRODUTOS_ABAIXO_MINIMO
 WHERE UNIDADE = 'UND'

-- CRIAR UMA VIEW PARA MOSTRAR O
-- NOME DO CLIENTE E A DATA DA ÚLTIMA VENDA REALIZADA
CREATE VIEW VW_CLIENTE_ULTIMA_VENDA
AS
SELECT NOMECLIENTE, MAX(V.DATAHORA) AS ULTIMAVENDA
  FROM CLIENTE C
 INNER JOIN VENDA V ON C.IDCLIENTE = V.IDCLIENTE
 GROUP BY C.NOMECLIENTE 

SELECT * FROM VW_CLIENTE_ULTIMA_VENDA