--============================================
-- FUNÇÃO NO BANCO DE DADOS
--============================================
CREATE FUNCTION FNC_FORMATA_CPFCNPJ(@STR VARCHAR(14))
 RETURNS VARCHAR(18)
AS
BEGIN
	DECLARE @RETORNO VARCHAR(18)

	-- VERIFICA SE O TAMANHO DO DADO INFORMADO TEM
	-- 11 (CPF) OU 14 (CNPJ) DÍGITOS
	IF (LEN(@STR) <> 11 AND LEN(@STR) <> 14)
	BEGIN
		SET @RETORNO = @STR -- SEM FORMATAÇÃO
	END
	ELSE IF (LEN(@STR) = 11)	-- CPF
	BEGIN
		SET @RETORNO =
			SUBSTRING(@STR, 1, 3) + '.' +
			SUBSTRING(@STR, 4, 3) + '.' +
			SUBSTRING(@STR, 7, 3) + '-' +
			SUBSTRING(@STR, 10, 2)
	END
	ELSE	-- CNPJ
	BEGIN
		SET @RETORNO = 
			SUBSTRING(@STR,  1, 2) + '.' +
			SUBSTRING(@STR,  3, 3) + '.' +
			SUBSTRING(@STR,  6, 3) + '/' +
			SUBSTRING(@STR,  9, 4) + '-' +
			SUBSTRING(@STR, 13, 2)
	END
	-- RETORNA A VARIÁVEL LOCAL
	RETURN @RETORNO
END


-- UTILIZAÇÃO DA FUNÇÃO
SELECT NOMECLIENTE, CPFCNPJ,
	DBO.FNC_FORMATA_CPFCNPJ(CPFCNPJ) AS FORMATADO
  FROM CLIENTE




