

--EXERCICIO 01--
ALTER TABLE EXEMPLAR ADD CONSTRAINT CHK_T01
 CHECK (SITUACAO = 'L' OR SITUACAO = 'E' OR SITUACAO = 'R' OR SITUACAO = 'M')
 
 --EXERCICIO 02--
CREATE TRIGGER TRG_EMPRESTAR
	ON EXEMPLAR AFTER INSERT, UPDATE
AS
BEGIN
	DECLARE
	@SITUACAO CHAR
	SELECT @SITUACAO = SITUACAO FROM inserted
	IF (@SITUACAO = 'L')
	UPDATE EXEMPLAR SET SITUACAO = @SITUACAO
	ELSE
	ROLLBACK
END
GO

--EXERCICIO 03--
CREATE TRIGGER TRG_DATA_DEV
	ON EMPRESTIMO_OBRA AFTER INSERT
AS
BEGIN
	DECLARE	@DATAPREV DATE
	DECLARE @IDEMPRESTIMO INT
	
	SELECT @DATAPREV = DATA_PREV_DEVOLUCAO FROM inserted
	SELECT @IDEMPRESTIMO = ID_EMPRESTIMO FROM inserted
	SET @DATAPREV = (SELECT DATEADD(DAY,5,@DATAPREV))
	UPDATE EMPRESTIMO_OBRA
	SET DATA_PREV_DEVOLUCAO = @DATAPREV WHERE @IDEMPRESTIMO = ID_EMPRESTIMO
END

--EXERCICIO 04--
ALTER TRIGGER TRG_DEV_EMPRESTIMO
	ON EXEMPLAR AFTER UPDATE, INSERT
AS
BEGIN
	DECLARE @IDOBRA INT
	DECLARE @IDEXEMPLAR INT
	DECLARE @SITUACAO CHAR
	DECLARE @IDEX_EMPR_OBRA INT
	DECLARE @DTDEV DATE
	DECLARE @DATA_PREV_DEV DATE
	
	SELECT @IDOBRA = ID_OBRA FROM inserted
	SELECT @IDEXEMPLAR = ID_EXEMPLAR FROM inserted
	SELECT @SITUACAO = SITUACAO FROM inserted
	SELECT @IDEX_EMPR_OBRA = ID_EXEMPLAR FROM EMPRESTIMO_OBRA
	SELECT @DTDEV = DATA_DEVOLUCAO FROM EMPRESTIMO_OBRA
	SELECT @DATA_PREV_DEV = DATA_PREV_DEVOLUCAO FROM EMPRESTIMO_OBRA
	
	if(@DTDEV > @DATA_PREV_DEV)
	BEGIN
		PRINT'DATA DE DEVOLUÇÃO ATRASADA'
		UPDATE EXEMPLAR
		SET SITUACAO = 'E'
		WHERE @IDEXEMPLAR = ID_EXEMPLAR
	END
	ELSE
	BEGIN
		PRINT'DATA DE DEVOLUÇÃO DENTRO DO PRAZO'
		UPDATE EXEMPLAR
			SET SITUACAO = 'E'
			WHERE @IDEXEMPLAR = ID_EXEMPLAR
	END
END
	
	

