

--EXERCICIO 01--
ALTER TABLE EXEMPLAR ADD CONSTRAINT CHK_T01
 CHECK (SITUACAO = 'L' OR SITUACAO = 'E' OR SITUACAO = 'R' OR SITUACAO = 'M')
 
 --EXERCICIO 02--
CREATE TRIGGER TRG_EMPRESTAR
	ON EXEMPLAR AFTER INSERT, UPDATE
AS
BEGIN
	DECLARE
	@SITUACAO CHAR
	SELECT @SITUACAO = SITUACAO FROM inserted
	IF (@SITUACAO = 'L')
	UPDATE EXEMPLAR
	SET SITUACAO = @SITUACAO
	ELSE
	ROLLBACK
END

--EXERCICIO 03--
CREATE TRIGGER TRG_DATA_DEV
	ON EMPRESTIMO_OBRA AFTER INSERT
AS
BEGIN
	DECLARE
	@DATAPREV DATE
	SELECT @DATAPREV = DATA_PREV_DEVOLUCAO FROM inserted
	UPDATE EMPRESTIMO_OBRA
	SET @DATAPREV = (SELECT DATEADD(DAY,5,GETDATE()))
	UPDATE EMPRESTIMO_OBRA
	SET DATA_PREV_DEVOLUCAO = @DATAPREV
END
