

--EXERCICIO 01--
ALTER TABLE EXEMPLAR ADD CONSTRAINT CHK_T01
 CHECK (SITUACAO = 'L' OR SITUACAO = 'E' OR SITUACAO = 'R' OR SITUACAO = 'M')
 
 --======================================================================================================
 --Criar uma trigger para verificar se um exemplar pode ser emprestado, 
 --se não puder então deve emitir uma mensagem de erro, se puder, então pode deixar emprestá-lo. 
 --Obs: um exemplar só pode ser emprestado se estiver marcado como situação ‘L’.
 --EXERCICIO 02--
ALTER TRIGGER TRG_EMPRESTAR
	ON EXEMPLAR AFTER INSERT, UPDATE
AS
--VARIÁVEIS LOCAIS--
	DECLARE	@SITUACAO CHAR
	DECLARE @NOVASITU CHAR
	DECLARE @ID INT
BEGIN
	SELECT @SITUACAO = SITUACAO FROM deleted
	SELECT @NOVASITU = SITUACAO,
		   @ID = ID_EXEMPLAR FROM inserted
	IF (@SITUACAO = 'L')
	UPDATE EXEMPLAR SET SITUACAO = @NOVASITU
	ELSE
	ROLLBACK
END
GO
SELECT * FROM EXEMPLAR

UPDATE EXEMPLAR SET SITUACAO = 'L' WHERE ID_EXEMPLAR = 1

--EXERCICIO 03--
CREATE TRIGGER TRG_DATA_DEV
	ON EMPRESTIMO_OBRA AFTER INSERT
AS
BEGIN
	DECLARE	@DATAPREV DATE
	DECLARE @IDEMPRESTIMO INT
	
	SELECT @DATAPREV = DATA_PREV_DEVOLUCAO FROM inserted
	SELECT @IDEMPRESTIMO = ID_EMPRESTIMO FROM inserted
	SET @DATAPREV = (SELECT DATEADD(DAY,5,@DATAPREV))
	UPDATE EMPRESTIMO_OBRA
	SET DATA_PREV_DEVOLUCAO = @DATAPREV WHERE @IDEMPRESTIMO = ID_EMPRESTIMO
END

--EXERCICIO 04--
ALTER TRIGGER TRG_DEV_EMPRESTIMO
	ON EXEMPLAR AFTER UPDATE, INSERT
AS
BEGIN
	DECLARE @IDOBRA INT
	DECLARE @IDEXEMPLAR INT
	DECLARE @SITUACAO CHAR
	DECLARE @IDEX_EMPR_OBRA INT
	DECLARE @DTDEV DATE
	DECLARE @DATA_PREV_DEV DATE
	
	SELECT @IDOBRA = ID_OBRA FROM inserted
	SELECT @IDEXEMPLAR = ID_EXEMPLAR FROM inserted
	SELECT @SITUACAO = SITUACAO FROM inserted
	SELECT @IDEX_EMPR_OBRA = ID_EXEMPLAR FROM EMPRESTIMO_OBRA
	SELECT @DTDEV = DATA_DEVOLUCAO FROM EMPRESTIMO_OBRA
	SELECT @DATA_PREV_DEV = DATA_PREV_DEVOLUCAO FROM EMPRESTIMO_OBRA WHERE @IDEXEMPLAR = ID_EXEMPLAR
	
	if(@DTDEV > @DATA_PREV_DEV)
	BEGIN
		PRINT'DATA DE DEVOLUÇÃO ATRASADA'
		UPDATE EXEMPLAR
		SET SITUACAO = 'E'
		WHERE @IDEXEMPLAR = ID_EXEMPLAR
	END
	ELSE
	BEGIN
		PRINT'DATA DE DEVOLUÇÃO DENTRO DO PRAZO'
		UPDATE EXEMPLAR
			SET SITUACAO = 'E'
			WHERE @IDEXEMPLAR = ID_EXEMPLAR
	END
END

--EXERCICO 5--
CREATE PROCEDURE SP_QUANTOS
	@IDALUNO INT, 
	@TOTAL INT OUTPUT
	
AS
SET @TOTAL = (SELECT COUNT(*)
		FROM EXEMPLAR AS EX
		INNER JOIN EMPRESTIMO_OBRA AS EO
			ON EX.ID_EXEMPLAR = EO.ID_EXEMPLAR
		INNER JOIN EMPRESTIMO AS EM
			ON EO.ID_EMPRESTIMO = EM.ID_EMPRESTIMO
		WHERE EM.ID_ALUNO = @IDALUNO)
		
--EXECUÇÃO--
DECLARE @T INT

EXEC SP_QUANTOS 5, @T OUTPUT

PRINT 'TOTAL DE EXEMPLARES EMRPRESTADOS'
PRINT @T

--EXERCICIO 6--
CREATE PROCEDURE SP_QUAIS
	@IDALUNO INT
AS
SELECT *
	FROM EXEMPLAR AS EX, EMPRESTIMO_OBRA AS EO,
		EMPRESTIMO AS EM, OBRA AS OB
	WHERE EO.ID_EXEMPLAR = EX.ID_EXEMPLAR
		AND EM.ID_EMPRESTIMO = EO.ID_EMPRESTIMO
		AND OB.ID_OBRA = EX.ID_OBRA
		AND EM.ID_ALUNO = @IDALUNO
		
--EXECUÇÃO--

EXEC SP_QUAIS 1

--EXERCICIO 7--
CREATE PROCEDURE SP_EXEMPLARES
	@IDALUNO INT
AS
SELECT *
	FROM EXEMPLAR AS EX, EMPRESTIMO_OBRA AS EO,
		EMPRESTIMO AS EM
	WHERE EO.ID_EXEMPLAR = EX.ID_EXEMPLAR
		AND EM.ID_EMPRESTIMO = EO.ID_EMPRESTIMO
		AND EM.ID_ALUNO = @IDALUNO
		
EXEC SP_EXEMPLARES 2

--EXERCICIO 08--
CREATE TRIGGER TRG_SITUACAO
	ON EXEMPLAR AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @IDEXEMPLAR INT
	SELECT @IDEXEMPLAR = ID_EXEMPLAR FROM EXEMPLAR 
	UPDATE EXEMPLAR 
	SET SITUACAO = 'L' WHERE @IDEXEMPLAR = ID_EXEMPLAR
END

--EXERCICIO 09--

SELECT DATEDIFF(DAY,GETDATE(),'2016-08-05')

--EXERCICIO 10

SELECT DATEADD(YEAR,5,GETDATE())
	
	

